#!/usr/bin/env python3
"""
MESWA page helper.        Run:  python build.py [--fix-names] [--optimize]

Scans your photo folders and writes photos.js, which index.html loads:
  images/          leader photos  -> dart around the screen, pause for the messages
  images/finals/   final photos   -> shown after the "Thank You, God" message

  --fix-names   rename files to safe names (lowercase, no spaces/odd characters)
  --optimize    shrink big photos (needs:  pip install pillow). Originals are
                backed up to _originals/ (don't upload that folder).
Re-run this every time you add, remove or rename photos.
"""
import json, re, shutil, sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
IMG, FIN = ROOT / "images", ROOT / "images" / "finals"
OK = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}
BAD = {".heic", ".heif", ".tif", ".tiff", ".bmp"}   # browsers can't show these
SHRINK = {".jpg", ".jpeg", ".png", ".webp"}
MAX_SIDE = {"leaders": 600, "finals": 1280}
BIG = 400 * 1024
args = set(sys.argv[1:])


def natural(p):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", p.name)]


def files(folder):
    if not folder.exists():
        return []
    return sorted((p for p in folder.iterdir() if p.is_file() and not p.name.startswith(".")), key=natural)


def clean(name):
    p = Path(name)
    stem = re.sub(r"[^a-z0-9]+", "-", p.stem.lower()).strip("-") or "photo"
    ext = p.suffix.lower()
    return stem + (".jpg" if ext == ".jpeg" else ext)


def fix_names(folder):
    for p in files(folder):
        if p.suffix.lower() not in OK | BAD:
            continue
        new = clean(p.name)
        if new == p.name:
            continue
        target, n = p.with_name(new), 2
        while target.exists() and target != p:
            target = p.with_name(f"{Path(new).stem}-{n}{Path(new).suffix}")
            n += 1
        p.rename(target)
        print(f"  renamed  {p.name}  ->  {target.name}")


def optimize(folder, kind):
    try:
        from PIL import Image, ImageOps
    except ImportError:
        sys.exit("--optimize needs Pillow:  pip install pillow")
    side = MAX_SIDE[kind]
    for p in files(folder):
        ext = p.suffix.lower()
        if ext not in SHRINK:
            continue
        with Image.open(p) as src:
            im = ImageOps.exif_transpose(src)   # fixes sideways phone photos
            im.load()
        if p.stat().st_size <= BIG and max(im.size) <= side:
            continue
        before = p.stat().st_size
        bak = ROOT / "_originals" / p.relative_to(ROOT)
        bak.parent.mkdir(parents=True, exist_ok=True)
        if not bak.exists():
            shutil.copy2(p, bak)
        im.thumbnail((side, side))
        if ext in (".jpg", ".jpeg"):
            im.convert("RGB").save(p, quality=82, optimize=True)
        elif ext == ".png":
            im.save(p, optimize=True)
        else:
            im.save(p, quality=82)
        print(f"  shrunk   {p.name}  {before // 1024}KB -> {p.stat().st_size // 1024}KB")


def scan(folder):
    good, warns = [], []
    for p in files(folder):
        ext = p.suffix.lower()
        rel = p.relative_to(ROOT).as_posix()
        if ext in BAD:
            warns.append(f"{rel}: {ext} can't be shown in browsers - convert it to JPG")
            continue
        if ext not in OK:
            continue
        if not re.fullmatch(r"[a-z0-9._-]+", p.name):
            warns.append(f"{rel}: odd characters/capitals in name - run with --fix-names")
        if p.stat().st_size > BIG:
            warns.append(f"{rel}: {p.stat().st_size // 1024}KB is heavy for mobile data - run with --optimize")
        good.append(p)
    return good, warns


def main():
    IMG.mkdir(exist_ok=True)
    FIN.mkdir(exist_ok=True)
    if "--fix-names" in args:
        print("Fixing names...")
        fix_names(IMG)
        fix_names(FIN)
    if "--optimize" in args:
        print("Optimizing...")
        optimize(IMG, "leaders")
        optimize(FIN, "finals")

    leaders, w1 = scan(IMG)
    finals, w2 = scan(FIN)
    warns = w1 + w2
    url = lambda p: quote(p.relative_to(ROOT).as_posix())

    js = "// Generated by build.py - re-run it whenever you add or remove photos.\n"
    js += f"var LEADER_IMGS={json.dumps([url(p) for p in leaders], indent=1)};\n"
    js += f"var FINAL_IMGS={json.dumps([url(p) for p in finals], indent=1)};\n"
    (ROOT / "photos.js").write_text(js, encoding="utf-8")

    mb = lambda ps: sum(p.stat().st_size for p in ps) / 1048576
    print("\n=== MESWA photo check ===")
    print(f"Leaders (images/):         {len(leaders):>3} photos, {mb(leaders):.1f}MB")
    for p in leaders:
        print("   ", p.name)
    print(f"Finals  (images/finals/):  {len(finals):>3} photos, {mb(finals):.1f}MB")
    for p in finals:
        print("   ", p.name)
    if finals:
        print(f"   finals will play for about {len(finals) * (1.9 if len(finals) > 10 else 2.5):.0f} seconds")

    todo = []
    html = ROOT / "index.html"
    if not html.exists():
        todo.append("index.html is missing from this folder")
    elif "photos.js" not in html.read_text(encoding="utf-8"):
        todo.append("index.html does not load photos.js - replace it with the new index.html")
    if not leaders:
        todo.append("add leader photos (jpg/png/webp) directly inside images/")
    if not finals:
        todo.append("add your final photos inside images/finals/")
    if len(finals) > 16:
        todo.append("more than 16 finals will be a long show - consider trimming")
    for label, items in (("Fix", warns), ("To do", todo)):
        if items:
            print(f"\n{label}:")
            for w in items:
                print("  -", w)
    if not warns and not todo:
        print("\nAll good. Open index.html to preview, then upload everything (including photos.js) to GitHub.")
    else:
        print("\nphotos.js written. Fix the points above, then run build.py again.")


main()