// Generated by build.py - re-run it whenever you add or remove photos.
var LEADER_IMGS=[
 "images/01.jpg",
 "images/02.jpg",
 "images/03.jpg",
 "images/04.jpg",
 "images/05.jpg",
 "images/06.jpg",
 "images/07.jpg",
 "images/08.jpg",
 "images/09.jpg",
 "images/10.jpg"
];
var FINAL_IMGS=[
 "images/finals/01.jpg",
 "images/finals/02.jpg",
 "images/finals/03.jpg",
 "images/finals/04.jpg",
 "images/finals/05.jpg"
];
